variables:

stages:
  - container
  - build

build-container:
  stage: container
  image: docker:dind
  only:
    - master
  script:
    - docker build -f Dockerfile -t gnunet-python .

# For now just build with python3
# language: python
# python:
#    - "3.6"
#    - "2.7"

build-gnunet-python:
  stage: build
  image: gnunet-python:latest
  only:
    - master
  before_script:
    - apt install python3-pip
    - pip3 install dbus
    - pip3 install PyGObject
  script: python setup.py
