variables:

stages:
  - container
  - build

build-container:
  stage: container
  image: docker:dind
  only:
    - master
  script:
    - docker build -f Dockerfile -t gnunet-python .

# For now just build with python3
# language: python
# python:
#    - "3.6"
#    - "2.7"

build-gnunet-python:
  stage: build
  image: gnunet-python:latest
  only:
    - master
  before_script:
    - apt-get install -y python3-pip python-gi python-gi-cairo python3-gi python3-gi-cairo gir1.2-gtk-3.0 dbus-python
  script: python setup.py
