types = set([
    "any",
    "fs_dblock",
    "fs_iblock",
    "fs_kblock",
    "fs_sblock",
    "fs_nblock",
    "fs_ondemand",
    "dht_hello",
    "test",
    "fs_ublock",
    "dns",
    "gns_namerecord",
    "regex",
    "regex_accept"])
